apiVersion: v1
kind: Service
metadata:
  name: booking-service-db
spec:
  ports:
    - port: 27017
  selector:
    app: booking-service-db
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  ports:
  - port: 8080
  selector:
    app: booking-service

